# Generated by Django 3.1.4 on 2020-12-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hased_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
