# Generated by Django 3.1.4 on 2020-12-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20201220_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='user',
        ),
    ]
