# Generated by Django 3.1.4 on 2020-12-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20201225_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'default_related_name': 'contact_information'},
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_information', serialize=False, to='hosts.host'),
        ),
    ]
