# Generated by Django 3.1.4 on 2020-12-20 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('noise_level', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=400)),
                ('office_type', models.CharField(max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
            options={
                'db_table': '"Office"',
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postal_code', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"OfficeLocation"',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('office_type', models.CharField(max_length=10)),
                ('hourly_rate', models.CharField(max_length=15)),
                ('monthly_rate', models.CharField(max_length=15)),
            ],
            options={
                'db_table': '"Pricing"',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmeneties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wifi', models.BooleanField(default=False)),
                ('outlet', models.BooleanField(default=False)),
                ('monitor', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('coffee', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('parking_cost', models.PositiveIntegerField()),
                ('elevator', models.BooleanField(default=False)),
                ('wheel_chir_access', models.BooleanField(default=False)),
                ('adjustable_seating', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"PropertyAmeneties"',
            },
        ),
        migrations.CreateModel(
            name='OfficeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('review_comment', models.CharField(max_length=200)),
                ('recommendation', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': '"OfficeReview"',
            },
        ),
        migrations.CreateModel(
            name='OfficeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_bucket_link', models.URLField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
            ],
            options={
                'db_table': '"OfficeImage"',
            },
        ),
        migrations.CreateModel(
            name='OfficeBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_booking', models.DateField()),
                ('end_booking', models.DateField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': '"OfficeBooking"',
            },
        ),
        migrations.AddField(
            model_name='office',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.officelocation'),
        ),
        migrations.AddField(
            model_name='office',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.pricing'),
        ),
        migrations.AddField(
            model_name='office',
            name='property_ameneties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.propertyameneties'),
        ),
    ]
